smpclClassifieldBundle:
    resource: "@smpclClassifieldBundle/Resources/config/routing.yml"
    prefix:   /avisos
smpclClassifieldBundle:
    resource: "@smpclClassifieldBundle/Resources/config/routing/classifield.yml"
    prefix:   /aviso
smpclUserBundle:
    resource: "@smpclUserBundle/Resources/config/routing.yml"
    prefix:   /

smpclThemeBundle:
    resource: "@smpclThemeBundle/Resources/config/routing.yml"
    prefix:   /
    
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
