parameters:
#    smpcl_theme.example.class: smpcl\ThemeBundle\Example

services:
#    smpcl_theme.example:
#        class: %smpcl_theme.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
