smpclClassifieldBundle_classifield:
    resource: "@smpclClassifieldBundle/Resources/config/routing/classifield.yml"
    prefix:   /avisos/
    
category_show:
    pattern:  /cat/{slug}/
    defaults: { _controller: "smpclClassifieldBundle:Category:show" }