parameters:
#    smpcl_classifield.example.class: smpcl\ClassifieldBundle\Example

services:
#    smpcl_classifield.example:
#        class: %smpcl_classifield.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
